# Generated by Django 5.2.8 on 2025-12-01 15:51

import django.contrib.auth.models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否逻辑删除', verbose_name='是否逻辑删除')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, help_text='用户账号', max_length=64, unique=True, verbose_name='用户账号')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=60, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, help_text='电话', max_length=30, null=True, verbose_name='电话')),
                ('avatar', models.CharField(blank=True, help_text='头像', max_length=200, null=True, verbose_name='头像')),
                ('name', models.CharField(help_text='姓名', max_length=40, verbose_name='姓名')),
                ('nickname', models.CharField(blank=True, default='', help_text='用户昵称', max_length=100, null=True, verbose_name='用户昵称')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, '未知'), (1, '女'), (2, '男')], default=0, help_text='性别', null=True, verbose_name='性别')),
                ('login_error_nums', models.IntegerField(default=0, help_text='登录错误次数', verbose_name='登录错误次数')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='钱包余额')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('is_guest', models.BooleanField(default=False, verbose_name='是否游客模式')),
                ('system_user_id', models.BigIntegerField(blank=True, help_text='当前账号的企业用户', null=True, verbose_name='system.Users.ID')),
            ],
            options={
                'verbose_name': '全局用户表',
                'verbose_name_plural': '全局用户表',
                'db_table': 'glboal_users',
                'ordering': ('-create_datetime',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否逻辑删除', verbose_name='是否逻辑删除')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='客户编码')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='付费截止日期')),
                ('on_trial', models.BooleanField(default=True, verbose_name='是否在试用期')),
                ('trial_end', models.DateField(blank=True, null=True, verbose_name='试用期结束日期')),
            ],
            options={
                'verbose_name': '基本模型',
                'verbose_name_plural': '基本模型',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalUserClientRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否逻辑删除', verbose_name='是否逻辑删除')),
                ('system_user_id', models.BigIntegerField(help_text='关联租户下的用户ID', verbose_name='system.Users.ID')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否激活状态')),
                ('active_datetime', models.DateTimeField(blank=True, null=True, verbose_name='激活时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.client', verbose_name='关联租户')),
                ('globalUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '租户-全局用户的关联记录',
                'verbose_name_plural': '租户-全局用户的关联记录',
            },
        ),
        migrations.AddField(
            model_name='globalusers',
            name='clients',
            field=models.ManyToManyField(related_name='global_users', through='tenants.GlobalUserClientRelation', to='tenants.client', verbose_name='当前账号的租户关联信息'),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否逻辑删除', verbose_name='是否逻辑删除')),
                ('username', models.CharField(blank=True, help_text='登录用户名', max_length=32, null=True, verbose_name='登录用户名')),
                ('ip', models.CharField(blank=True, help_text='登录ip', max_length=32, null=True, verbose_name='登录ip')),
                ('agent', models.CharField(blank=True, help_text='agent信息', max_length=1500, null=True, verbose_name='agent信息')),
                ('browser', models.CharField(blank=True, help_text='浏览器名', max_length=200, null=True, verbose_name='浏览器名')),
                ('os', models.CharField(blank=True, help_text='操作系统', max_length=150, null=True, verbose_name='操作系统')),
                ('login_type', models.IntegerField(choices=[(1, '后台登录')], default=1, help_text='登录类型', verbose_name='登录类型')),
                ('ip_area', models.CharField(blank=True, help_text='IP归属地', max_length=100, null=True, verbose_name='IP归属地')),
                ('msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义内容')),
                ('status', models.BooleanField(default=True, help_text='响应状态', verbose_name='响应状态')),
                ('global_user', models.ForeignKey(blank=True, help_text='全局用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='全局用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_log',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
