# Generated by Django 5.2.8 on 2025-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='是否在试用期'),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='付费截止日期'),
        ),
        migrations.AlterField(
            model_name='client',
            name='trial_end',
            field=models.DateField(blank=True, null=True, verbose_name='试用期结束日期'),
        ),
    ]
