# Generated by Django 5.2.8 on 2025-11-24 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_client_on_trial_alter_client_paid_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否逻辑删除', verbose_name='是否逻辑删除')),
                ('username', models.CharField(blank=True, help_text='登录用户名', max_length=32, null=True, verbose_name='登录用户名')),
                ('ip', models.CharField(blank=True, help_text='登录ip', max_length=32, null=True, verbose_name='登录ip')),
                ('agent', models.CharField(blank=True, help_text='agent信息', max_length=1500, null=True, verbose_name='agent信息')),
                ('browser', models.CharField(blank=True, help_text='浏览器名', max_length=200, null=True, verbose_name='浏览器名')),
                ('os', models.CharField(blank=True, help_text='操作系统', max_length=150, null=True, verbose_name='操作系统')),
                ('login_type', models.IntegerField(choices=[(1, '后台登录')], default=1, help_text='登录类型', verbose_name='登录类型')),
                ('ip_area', models.CharField(blank=True, help_text='IP归属地', max_length=100, null=True, verbose_name='IP归属地')),
                ('msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义内容')),
                ('status', models.BooleanField(default=True, help_text='响应状态', verbose_name='响应状态')),
                ('global_user', models.ForeignKey(blank=True, help_text='全局用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='全局用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_log',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
