# Generated by Django 5.2.7 on 2025-12-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MConversation',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='会话编码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='会话名称')),
                ('deleting', models.BooleanField(default=False, verbose_name='是否删除')),
                ('editing', models.BooleanField(default=False, verbose_name='是否编辑中')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to='system.users', verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'AI会话',
                'verbose_name_plural': 'AI会话',
                'db_table': 'ai_conversations',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MConversationLog',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('begin_time', models.DateTimeField(blank=True, help_text='生产时间', null=True, verbose_name='生产时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('role', models.CharField(blank=True, max_length=32, null=True, verbose_name='角色')),
                ('ltype', models.CharField(blank=True, max_length=32, null=True, verbose_name='会话类型')),
                ('meno', models.TextField(verbose_name='会话内容')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to='system.users', verbose_name='创建人')),
                ('mConversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeplan.mconversation', verbose_name='会话信息')),
            ],
            options={
                'verbose_name': 'AI会话记录',
                'verbose_name_plural': 'AI会话记录',
                'db_table': 'ai_conversations_logs',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
